version: '3.8'

services:
  db:
    image: postgres_ci_cd_image:latest
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hasina
      POSTGRES_DB: ma_base
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: